[CLDN-1289] Do not display results if cidr is passed
CybercentreCanada/superset pull request #100
Opened 2022-04-01 14:53 UTC by cccs-RyanS

### SUMMARY

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TESTING INSTRUCTIONS

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2022-04-01 15:18 UTC, cccs-Dustin approved these changes

2022-04-04 12:43 UTC, dparent1 requested changes

2022-04-04 12:43 UTC, dparent1 commented on superset-frontend/src/cccs-viz/plugins/plugin-chart-at-a-glance-dns/src/AtAGlanceDns.tsx
> +          <span>DNS At A Glance chart not avialable for CIDR ranges. Please input a single IP address to use this chart.</span>
available, not avialable. (small typo)

2022-04-04 12:43 UTC, cccs-RyanS commented on superset-frontend/src/cccs-viz/plugins/plugin-chart-at-a-glance-dns/src/AtAGlanceDns.tsx
> +          <span>DNS At A Glance chart not avialable for CIDR ranges. Please input a single IP address to use this chart.</span>
Man I really need spell check

2022-04-11 13:09 UTC, dparent1 approved these changes

2022-04-19 12:11 UTC, merged