Feature/cldn 1282
CybercentreCanada/superset pull request #101
Opened 2022-04-01 15:17 UTC by cccs-Dustin

### SUMMARY

This is the PR for the associated CLDN-1282 task

Changes include adding a new endpoint to the back-end that serves as a proxy to Alfred, as well as the modification of the Application Links viz to work with this new endpoint. The control panel of the Application Links viz was also modified so that the chart will display properly regardless of the dataset that it is made on.

It is not seen in this PR, but I also had to edit the extra-ca-certs Kubernetes secret on the PB-stg cluster by adding in a .pem file from the Alfred website. 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

N/A

### TESTING INSTRUCTIONS

N/A

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [X] Introduces new feature or API
- [ ] Removes existing feature or API

2022-04-04 13:02 UTC, dparent1 requested changes
I'd like to see an __init__ method in the class unless there is a strong reason to avoid one.

2022-04-04 15:51 UTC, cccs-Dustin commented on superset/proxy/api.py
> +    ALFRED_SCOPE = os.environ.get("ALFRED_SCOPE")
I can definitely do that, the __init__ method will look like:

`def __init__(self):
        """
        This is the init function for the ProxyRestAPI class
        """
        super().__init__()
        self.user = current_user

        self.ALFRED_SCOPE = os.environ.get("ALFRED_SCOPE")
        if self.ALFRED_SCOPE is None:
            self.ALFRED_SCOPE = "api://alfred.pb/Alfred.ALL"

        self.ALFRED_URL = os.environ.get("ALFRED_URL")
        if self.ALFRED_URL is None:
            self.ALFRED_URL = "https://alfred-stg-pb.chimera.cyber.gc.ca"

        self.SSL_CERT = os.environ.get("REQUESTS_CA_BUNDLE")`

2022-04-06 12:20 UTC, dparent1 approved these changes

2022-06-17 15:43 UTC, cccs-Dustin commented
Closing this PR as I will open another one on the cccs-1.5 branch

2022-06-17 15:43 UTC, cccs-Dustin commented
Closing this PR as I will open another one on the cccs-1.5 branch

2022-06-17 15:43 UTC, closed without merging