Add row number option to CCCS-Grid
CybercentreCanada/superset pull request #181
Opened 2022-07-21 14:44 UTC by reesercollins

### SUMMARY

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TESTING INSTRUCTIONS

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://cccs.atlassian.net/browse/CLDN-1556
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2022-07-21 18:00 UTC, cccs-Dustin requested changes

2022-07-21 18:06 UTC, reesercollins commented on superset-frontend/src/cccs-viz/plugins/plugin-chart-cccs-grid/test/plugin/buildQuery.test.ts
> +    enable_row_numbers: false,
These are tests that are never run. I just put those values there to stop the build from failing.

2022-07-21 18:06 UTC, reesercollins commented on superset-frontend/src/cccs-viz/plugins/plugin-chart-cccs-grid/test/plugin/transformProps.test.ts
> +    enable_row_numbers: false,
Same as previous comment.

2022-07-21 18:51 UTC, cccs-Dustin approved these changes

2022-07-25 16:46 UTC, cccs-RyanK approved these changes

2022-07-25 17:16 UTC, merged