Feature/cldn 1749
CybercentreCanada/superset pull request #222
Opened 2022-11-01 13:05 UTC by cccs-RyanS

### SUMMARY

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TESTING INSTRUCTIONS

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2022-11-15 15:29 UTC, cccs-Dustin requested changes
Other than my one comment, lgtm!

2022-11-15 15:29 UTC, cccs-Dustin commented on cccs-build/superset/Dockerfile
> +
```suggestion
FROM uchimera.azurecr.io/cccs/superset-base:cccs-2.0_20221014182839_b5135

```
This change should be reverted before we merge into `cccs-2.0`

2022-11-21 18:58 UTC, cccs-Dustin approved these changes

2022-12-01 13:18 UTC, cccs-RyanK approved these changes

2022-12-01 13:57 UTC, merged