Feature/cldn 1932 update cccs main to 2.0.1 add cccs 2.0
CybercentreCanada/superset pull request #257
Opened 2023-02-08 14:41 UTC by cccs-RyanK

### SUMMARY

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TESTING INSTRUCTIONS

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2023-02-08 15:09 UTC, cccs-Dustin approved these changes
Assuming QA brings up no issues, it lgtm!

2023-02-09 16:48 UTC, cccs-joel requested changes

2023-02-10 14:52 UTC, cccs-RyanK commented on docker-compose.yml
> +x-superset-image: &superset-image apache/superset:2.0.0
fixed it!

2023-02-14 14:12 UTC, cccs-joel approved these changes

2023-02-14 14:17 UTC, merged