Feature/cldn 1968 (Display JSON data inline)
CybercentreCanada/superset pull request #268
Opened 2023-03-07 14:18 UTC by cccs-Dustin

This PR incorporates the changes requested in the CLDN-2000 ticket ([link](https://cccs.atlassian.net/browse/CLDN-2000))

**Major Changes Include:**
- Updated version of the `CCCS-Grid` which now displays JSON data inline
- Modified multiple files when running the `pre-commit` hook

2023-03-08 14:53 UTC, cccs-RyanK approved these changes

2023-03-08 17:00 UTC, cccs-rc requested changes
Requesting changes just for the TODOs. I'm not too concerned about the other nitpicks.

2023-03-08 19:43 UTC, cccs-Dustin commented on superset-frontend/src/cccs-viz/plugins/plugin-chart-cccs-grid/src/plugin/controlPanel.tsx
> +                    // TODO properly ensure is Bool
Removed the 'TODO's in the latest commit

2023-03-08 19:43 UTC, cccs-Dustin commented on superset-frontend/src/cccs-viz/plugins/plugin-chart-cccs-grid/src/plugin/controlPanel.tsx
> +            // TODO properly ensure is Bool
Removed the 'TODO's in the latest commit

2023-03-08 19:43 UTC, cccs-Dustin commented on superset-frontend/src/cccs-viz/plugins/plugin-chart-cccs-grid/src/plugin/controlPanel.tsx
> +            // TODO properly ensure is Bool
Removed the 'TODO's in the latest commit

2023-03-08 19:45 UTC, cccs-Dustin commented on superset-frontend/src/cccs-viz/plugins/plugin-chart-cccs-grid/src/ExpandAllValueRenderer.tsx
> +    const jsonCells = newInstances.map((instance: any) =>
Ranamed the variable to be equal to `jsonCellExpandedValues` in the most recent commit.

2023-03-08 20:57 UTC, cccs-Dustin commented on superset-frontend/src/cccs-viz/plugins/plugin-chart-cccs-grid/src/ExpandAllValueRenderer.tsx
> +    }
Not too sure why the pre-commit hook didn't pick this up. I added the change (to multiple locations) in one of the most recent commits.

2023-03-08 21:32 UTC, cccs-rc approved these changes

2023-03-15 16:29 UTC, cccs-RyanS approved these changes

2023-03-15 18:08 UTC, merged