Feature/cccs 1.2 gwwk discovery
CybercentreCanada/superset pull request #28
Opened 2021-06-08 15:45 UTC by cccs-jc

### SUMMARY

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TEST PLAN

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2021-06-09 12:28 UTC, cccs-rc requested changes
My Java brain kinda wants to abstract some of the common code into a parent class or something but no idea how feasible that is or if it's in line with web-dev practices.

2021-06-09 12:28 UTC, cccs-rc commented on superset-frontend/src/cccs-viz/plugins/plugin-chart-gwwk-charts/test/index.test.ts
> +describe('@superset-ui/plugin-chart-iframe-demo', () => {
iframe-demo?

2021-06-09 12:28 UTC, cccs-rc commented on superset-frontend/src/cccs-viz/plugins/plugin-chart-gwwk-charts/test/plugin/transformProps.test.ts
> +  it('should tranform chart props for viz', () => {
```suggestion
  it('should transform chart props for viz', () => {
```

2021-06-11 15:21 UTC, cccs-rc approved these changes

2021-06-11 18:57 UTC, cccs-jc commented on superset-frontend/src/cccs-viz/plugins/plugin-chart-cccs-grid/src/CccsGrid.tsx
> +  }, [emitFilter, setDataMask]); // only take relevant page size options
yes. We will be re-visiting this code many times over and over time it will be cleaned up.

we are only at the beginning still

2021-06-11 18:58 UTC, merged