CLDN-2271 disable populating the value filter option
CybercentreCanada/superset pull request #366
Opened 2023-08-29 19:19 UTC by cccs-RyanK

### SUMMARY

This PR fixes a bug with the pre-filtering option in the value filter that looks to have been caused by a bad merge from release 2.1. It also adds an option to the control panel for the value filter that allows the user to disable "fetching" options as described in the CLDN-2271 ticket
### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TESTING INSTRUCTIONS

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2023-08-30 14:21 UTC, cccs-Dustin requested changes

2023-08-30 14:21 UTC, cccs-Dustin commented on cccs-build/superset/Dockerfile
> +FROM uchimera.azurecr.io/cccs/superset-base:CLDN-2271-disable-populating-the-value-filter-option_20230829194848_b7564
```suggestion
FROM uchimera.azurecr.io/cccs/superset-base:cccs-2.1_20230726145242_b7395
```
We shouldn't update this until the PR has been merged in

2023-08-30 14:55 UTC, cccs-rc approved these changes
Approved, since disabling some options that are less relevant when fetching is disabled will be handled with another PR.

2023-09-05 19:36 UTC, cccs-RyanK commented
I removed the control option to disable fetching values for the dropdown. This feature requires more design decisions and work so it will be left for another PR

2023-09-19 11:04 UTC, cccs-Dustin approved these changes

2023-09-19 12:30 UTC, merged