Feature/cldn 890
CybercentreCanada/superset pull request #39
Opened 2021-08-09 15:03 UTC by harman-sehra

### SUMMARY

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TEST PLAN

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2021-08-17 13:52 UTC, cccs-rc requested changes

2021-08-17 13:52 UTC, cccs-rc commented on superset-frontend/src/cccs-viz/plugins/plugin-chart-cccs-grid/src/CccsGrid.tsx
> +    suppressColumnVirtualisation: true
Is this the performance thing you're disabling? Might be worth a comment.

2021-08-17 13:52 UTC, cccs-rc commented on superset-frontend/src/cccs-viz/plugins/plugin-chart-cccs-grid/src/CccsGrid.tsx
> +  function autoSizeFirstColumns(params: any){
Tempted to name this autosizeFirst100Columns. Or at least add a comment to say we're autosizing the first 100.

2021-08-18 19:28 UTC, cccs-rc approved these changes

2021-08-19 12:17 UTC, cccs-RyanS approved these changes

2021-08-19 16:35 UTC, merged