Feature/flow8 Download Eml File
CybercentreCanada/superset pull request #421
Opened 2024-04-23 19:53 UTC by nz970

### SUMMARY
In relation to this ticket: https://cccs.atlassian.net/browse/CLDN-2163
Users should be able to right-click on a row containing a path to an EML file on the Email Harmonized Dashboard and retrieve that file via a dropdown menu item within Ag-grid.  The download will start and inform the user if the download was successful or not.  

Deliverables:
A deployment of Superset that allows users to retrieve EML files.
A version of the Email Triaging Dashboard that allows users to retrieve EML files.

### TESTING INSTRUCTIONS
1.  Go on Superset-stg
2.  In the main view, right click on a row and then click 'Download Email'
3. Download should start

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ x] Required feature flags:
- [ x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [x] Introduces new feature or API
- [ ] Removes existing feature or API

2024-04-23 20:57 UTC, cccs-joel requested changes
I feel something happened with the formatting here, could be related to prettier and lint, can you check?

2024-04-23 20:57 UTC, cccs-joel commented on superset-frontend/.gitignore
> +package.json
I think we need these files.

2024-04-24 13:23 UTC, cccs-RyanK requested changes
Make sure to undo all the changes to files except under superset-frontend/src/cccs-viz/plugins/plugin-chart-ag-grid/src, then it is good to go!

2024-04-24 20:23 UTC, cccs-rc requested changes

2024-04-24 20:23 UTC, cccs-rc commented on superset/advanced_data_type/plugins/eml_path.py
> +import re
I believe we want to store types in PB Gitlab now, since some types can't live in public Github.

2024-04-24 20:23 UTC, cccs-rc commented on superset-frontend/src/cccs-viz/plugins/plugin-chart-ag-grid/src/ag-grid/AGGridViz.tsx
> +          data={selectedData.typeData.eml_path[0]}
How does this handle multi-select?

2024-04-24 23:14 UTC, closed without merging